name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Comment to post on an individual's first issue
        issue-message: '# It looks like this is your first issue here. Welcome to my Hello World reposirory!'
        # Comment to post on an individual's first pull request
        pr-message: '# It looks like this is your first pull request here. Welcome to my Hello World repository!'
