name: Manual workflow

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Update System
      run: |
        sudo apt update
        sudo apt-get install unattended-upgrades -y
        sudo unattended-upgrades
       
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: List files
      run: ls
