name: Manual workflow

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Update System
      run: |
        sudo apt-get update
        sudo apt-get install unattended-upgrades -y
        sudo unattended-upgrades -d
       
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Create file
      run: echo "This is a file" > file.txt
      
    - name: List files
      run: ls -lah
